### PR TITLE
[cards] card-based UX for plans in a given Product

### PR DESCRIPTION
**Pull request by duggiemitchell**
## Cute animal pic
_Because everyone likes pictures of [animals](https://unsplash.com/t/animals)._

iStock-1078528248

## Link to Trello card (if applicable)

- https://trello.com/c/T8WvSzNy

## Description
_The commit messages say what you did; this should explain why and/or how._
- [x] Description is in Trello card

## Steps to test/reproduce

- In Django admin, edit product and select `layout -> "Card"`
- Select product --> view plans in card layout

## Show me
_Provide screenshots/animated gifs/videos if necessary._

Screen Shot 2020-11-04 at 4 14 47 PM

### CODE REVIEW

**Review by jgerigmeyer — APPROVED** [review]
This is looking good to me! @stacyk As far as I'm aware there are not any outstanding style issues, but I'd like your review.

**Comment by jgerigmeyer** [comment]
@duggiemitchell Not urgent, but I'd appreciate your review of the JS here since you wrote the initial code 👍

**Comment by jgerigmeyer** [comment]
@jerivas Requesting your review here to help ease you into this codebase. I can talk through the specific changes with you in more detail; as you can see the Python changes are relatively straightforward.

**Comment by jgerigmeyer** [comment]
[I want to see a simpler (card-based) UX for plans in a given Product.](https://trello.com/c/T8WvSzNy/159-i-want-to-see-a-simpler-card-based-ux-for-plans-in-a-given-product)

**Review by stacyk — APPROVED** [review]
🥇 LGTM

**Comment by stacyk** [comment]
[Bug: When logged out, steps table header has multi-colored background.](https://trello.com/c/AHsbXYqZ/178-bug-when-logged-out-steps-table-header-has-multi-colored-background)

**Comment by stacyk** [comment]
image
 I added some CSS to make sure this is always a gray thead bg

**Review by jgerigmeyer — APPROVED** [review]

**Review by jerivas — APPROVED** [review]

**Pull request merged**
