### PR TITLE
Ensure pip-tools is upgraded before other dependencies

### PR DESCRIPTION
**Pull request by jerivas**

### CODE REVIEW

**Comment by jerivas** [comment]
[Ensure pip-tools is updated to the latest version before other dependencies](https://trello.com/c/wa1sfErZ/205-ensure-pip-tools-is-updated-to-the-latest-version-before-other-dependencies)

**Review by jgerigmeyer — APPROVED** [review]
Looks good! We might as well backport this to Metecho and OddBooks as well, yes?

**Comment by jgerigmeyer** [comment]
> Looks good! We might as well backport this to Metecho and OddBooks as well, yes?

Ah, I guess maybe that's not needed because it's handled by the Dockerfile? I see it in Estimating Engine already, but not in Metecho or OddBooks.

**Comment by jerivas** [comment]
That's correct. The ones that use the `setup-docker` action don't need it because the Dockerfile installs the latest pip + pip-tools for us. Metecho actually ends up downgrading pip-tools because it's listed in the dev requirements

**Pull request merged**
