### PR TITLE
Allow manual ordering of plans in additional_plans

### PR DESCRIPTION
**Pull request by wlonk**
baby lynx curled up with adult dog

### CODE REVIEW

**Comment by wlonk** [comment]
[I want to specify a manual ordering of additional_plans on a Product.](https://trello.com/c/a89xMYo1/163-i-want-to-specify-a-manual-ordering-of-additionalplans-on-a-product)

**Comment by duggiemitchell** [comment]
@wlonk @jgerigmeyer I'm assigned here but not sure if there is any frontend needs on this pr. Can either confirm?

**Comment by wlonk** [comment]
I don't know; does this only get ordered through the admin?

**Comment by jgerigmeyer** [comment]
> @wlonk @jgerigmeyer I'm assigned here but not sure if there is any frontend needs on this pr. Can either confirm?

@duggiemitchell I think Kit is correct that the front end is not actually doing any sorting here currently, but just displaying them in the order they're returned from the API. But, since we're storing these plans as an object, I'd rather not rely on object-entry ordering. Probably best to sort on the front end at display-time, `listedAdditionalPlans` in `products/detail.tsx`.

**Pull request merged**
