### PR TITLE
switch to openpgp and ubuntu keyservers

### PR DESCRIPTION
**Pull request by dvdherron**
## Steps to test/reproduce
 - running `docker-compose build` or (`reopen in container` in VSCode) with the old keyservers fails
 - doing the same with the updated keyservers should succeed

Context: https://github.com/nodejs/docker-node/issues/1500#issuecomment-865693819

### CODE REVIEW

**Comment by jerivas** [comment]
[Fix broken keyservers](https://trello.com/c/th1SKZiC/187-fix-broken-keyservers)

**Comment by jerivas** [comment]
Thanks @dvdherron, I was able to reproduce the issue and your fix does indeed solve it. I actually think SFDO will want to take a look at this for security. Would you like to open an [upstream PR](https://github.com/SFDO-Tooling/MetaDeploy/compare/main...oddbird:fix-keyservers)?

**Comment by dvdherron** [comment]
> 
> 
> Thanks @dvdherron, I was able to reproduce the issue and your fix does indeed solve it. I actually think SFDO will want to take a look at this for security. Would you like to open an [upstream PR](https://github.com/SFDO-Tooling/MetaDeploy/compare/main...oddbird:fix-keyservers)?
> 
> (Happy to open the PR myself if you prefer, it just felt more appropriate for you to be the PR author since you're the committer)

@jerivas done: https://github.com/SFDO-Tooling/MetaDeploy/pull/2947 
Let me know if anything looks weird.

**Comment by jerivas** [comment]
@dvdherron looks good! I suggest drawing attention to the fact that docker builds are currently broken without this to make the severity clear.

**Review by jgerigmeyer — APPROVED** [review]

**Pull request merged**
