### PR TITLE
[storybook] add storybook 

### PR DESCRIPTION
**Pull request by dvdherron**
## Description
Adds Storybook to MetaDeploy for component documentation. 

## Steps to test/reproduce
Run storybook using `yarn storybook` or `./derrick storybook`
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

## Show me
_Provide screenshots/animated gifs/videos if necessary._

# REMEMBER: Attach this PR to the Trello card

### CODE REVIEW

**Comment by dvdherron** [comment]
[MetaDeploy: set up storybook](https://trello.com/c/8frEpbqQ/102-metadeploy-set-up-storybook)

**Comment by dvdherron** [comment]
@jgerigmeyer This is ready for review, I think. 
 
One issue is hot reloading. I'm seeing errors like this in the console:

> `[HMR] Update check failed: hotApply/<@http://localhost:6006/runtime~main.iframe.bundle.js:528:21
promise callback*hotApply@http://localhost:6006/runtime~main.iframe.bundle.js:527:39
cb@http://localhost:6006/vendors-node_modules_salesforce-ux_design-system_assets_icons_action-sprite_svg_symbols_svg-n-e84977.iframe.bundle.js:180938:36
check/

> Uncaught (in promise) Error: apply() is only allowed in ready status
    hotApply hot module replacement:279
    promise callback*hotApply hot module replacement:278
    cb process-update.js:76
    check process-update.js:91
    promise callback*check process-update.js:90
    exports process-update.js:52
    processMessage client.js:279
    handleMessage client.js:139
    handleMessage client.js:102

Is that a webpack setting that needs to be configured differently?

I wasn't sure if the `api_urls` were needed just yet, so I left them out of the `fixtures` file for now but I can add those if needed.

**Review by jgerigmeyer — APPROVED** [review]
@dvdherron Looks good!

> One issue is hot reloading. I'm seeing errors like this in the console

Yeah, I saw that on Metecho too. I think it's something with Storybook's (recent) support for Webpack v5. I'd say it's not a big deal, let's wait a bit and see if it goes away.

> I wasn't sure if the api_urls were needed just yet, so I left them out of the fixtures file for now but I can add those if needed.

Sure, that's fine. They'll be needed as soon as we document a component that tries to access `window.api_urls`.

**Review by stacyk — APPROVED** [review]
@dvdherron I was able to get this running locally without any issues and the content here is really helpful and very clear. 🎉

**Pull request merged**
